//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contro_de_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario()
        {
            this.detalle_orden = new HashSet<detalle_orden>();
        }
    
        public int idinventario { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idarticulo { get; set; }
        public Nullable<int> idproveedor { get; set; }
        public Nullable<int> idbodega { get; set; }
        public Nullable<int> idunidadmedida { get; set; }
        public string lote { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string estado { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual bodegas bodegas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_orden> detalle_orden { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual unidades_medida unidades_medida { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
