//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contro_de_Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventarioEntities : DbContext
    {
        public inventarioEntities()
            : base("name=inventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulos> articulos { get; set; }
        public virtual DbSet<bodegas> bodegas { get; set; }
        public virtual DbSet<detalle_orden> detalle_orden { get; set; }
        public virtual DbSet<envases> envases { get; set; }
        public virtual DbSet<formas_almacenaje> formas_almacenaje { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_movimiento> tipo_movimiento { get; set; }
        public virtual DbSet<unidades_medida> unidades_medida { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
