//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contro_de_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedores()
        {
            this.inventario = new HashSet<inventario>();
        }
    
        public int idproveedor { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string nombre { get; set; }
        public string nombre_comercial { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string nit { get; set; }
        public string nrc { get; set; }
        public string giro { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario> inventario { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
